scalar Date
type Sale{
    idSale: ID!
    idProduct: Int!
    quantity: Int!  
    idClient: Int! 
    idSeller: Int! 
    date: Date!
}

type Query {
    sales: [Sale!]
}

type Query {
    sale (id:Int!): Sale!
}

input NewSale{
    idProduct: Int!
    quantity: Int!  
    idClient: Int! 
    idSeller: Int!
}

type Mutation{
    createSale(input: NewSale!): Sale!
}

input UpdateSa{
    id: Int!
    idSeller: Int!
}

type Mutation{
    updateSale(input: UpdateSa): Sale!
}
