scalar Date
type Wishlist{
    idWish: ID!
    idProduct: Int!
    idCliente: Int!  
    date: Date!
}

type Query {
    wishlists: [Wishlist!]
}

input NewWishlist{
     idProduct: Int!
    idCliente: Int!
}

type Mutation{
    createWishlist(input: NewWishlist!): Wishlist!
}
