scalar Date
type Wishlist{
    idWish: ID!
    idProduct: Int!
    idCliente: Int!  
    date: Date!
}

type Query {
    wishlist (id: Int!): [Wishlist!]
}

input NewWishlist{
    idProduct: Int!
    idCliente: Int!
}

type Mutation{
    deleteWishlist(id: Int!): String!
}

type Mutation{
    createWishlist(input: NewWishlist!): Wishlist!
}
