scalar Date
type Product{
    idProduct: ID!
    name: String!
    price: Int! 
    date: Date! 
    offer: Boolean!
    offerPorcentaje: Int!
    active: Boolean!
}

type Query {
    products: [Product!]
}

type Query {
    product (id: Int!): Product!
}

input NewProduct{
    name: String! 
    price: Int!
}

type Mutation{
    createProduct(input: NewProduct!): Product!
}

type Mutation{
    deleteProduct(id: Int!): Product!
}

input UpdatePro{
    id: Int!
    name: String
    price: Int
}

type Mutation{
    updateProduct(input: UpdatePro): Product!
}